### PR TITLE
Restructure to support Sequel 5 plugin format

### PR DESCRIPTION
**Pull request by nhmood**
Upcoming Sequel 5 plugin format has changed and Sequel 4 throws
deprecation warnings due to it
Patched plugin structure to support new format

### CODE REVIEW

**Review by AlexWayfer — CHANGES_REQUESTED** [review]
Please, change [version of Sequel dependency](https://github.com/mlen/sequel_secure_password/blob/6d2e663/sequel_secure_password.gemspec#L26).

**Comment by bgentry** [comment]
I made a fix to the gemspec for this PR here https://github.com/nhmood/sequel_secure_password/pull/2

**Comment by AlexWayfer** [comment]
Great job, @nhmood! Now it's up to @mlen.

**Comment by mlen** [comment]
I merged a slightly modified version of this code, thanks :)

**Comment by mlen** [comment]
Version 0.2.15 is out

**Pull request closed without merging**
